-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.user_favorites (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID NOT NULL,
 drama_id UUID NOT NULL REFERENCES public.dramas(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(user_id, drama_id)
);

ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_own_favorites ON public.user_favorites FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_own_favorites ON public.user_favorites FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_delete_own_favorites ON public.user_favorites FOR DELETE USING (user_id = auth.uid());

