-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.comments (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 drama_id UUID NOT NULL REFERENCES public.dramas(id) ON DELETE CASCADE,
 user_id UUID,
 content TEXT NOT NULL,
 parent_id UUID REFERENCES public.comments(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_comments ON public.comments FOR SELECT USING (true);
CREATE POLICY anon_insert_comments ON public.comments FOR INSERT WITH CHECK (true);
CREATE POLICY users_update_own_comments ON public.comments FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY users_delete_own_comments ON public.comments FOR DELETE USING (user_id = auth.uid());

