-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.episodes (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 drama_id UUID NOT NULL REFERENCES public.dramas(id) ON DELETE CASCADE,
 episode_number INTEGER NOT NULL,
 title TEXT,
 video_url TEXT,
 duration INTEGER,
 is_free BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.episodes ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_episodes ON public.episodes FOR SELECT USING (true);

