-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.dramas (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 title TEXT NOT NULL,
 subtitle TEXT,
 cover_image TEXT,
 type TEXT NOT NULL,
 views INTEGER DEFAULT 0,
 is_free BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.dramas ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_dramas ON public.dramas FOR SELECT USING (true);

