-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.likes (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 drama_id UUID NOT NULL REFERENCES public.dramas(id) ON DELETE CASCADE,
 user_id UUID,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(drama_id, user_id)
);

ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_likes ON public.likes FOR SELECT USING (true);
CREATE POLICY anon_insert_likes ON public.likes FOR INSERT WITH CHECK (true);
CREATE POLICY users_delete_own_likes ON public.likes FOR DELETE USING (user_id = auth.uid());

