-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS public.user_watch_history (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID NOT NULL,
 drama_id UUID NOT NULL REFERENCES public.dramas(id) ON DELETE CASCADE,
 episode_id UUID REFERENCES public.episodes(id) ON DELETE SET NULL,
 last_watched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 progress_seconds INTEGER DEFAULT 0,
 UNIQUE(user_id, drama_id)
);

ALTER TABLE public.user_watch_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_own_watch_history ON public.user_watch_history FOR SELECT USING (user_id = auth.uid());
CREATE POLICY users_insert_own_watch_history ON public.user_watch_history FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY users_update_own_watch_history ON public.user_watch_history FOR UPDATE USING (user_id = auth.uid());

