/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as UnlockedRouteImport } from './routes/unlocked'
import { Route as WatchedRouteImport } from './routes/watched'
import { Route as DramaIdRouteImport } from './routes/drama.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockedRoute = UnlockedRouteImport.update({
  id: '/unlocked',
  path: '/unlocked',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchedRoute = WatchedRouteImport.update({
  id: '/watched',
  path: '/watched',
  getParentRoute: () => rootRouteImport,
} as any)
const DramaIdRoute = DramaIdRouteImport.update({
  id: '/drama/$id',
  path: '/drama/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/unlocked': typeof UnlockedRoute
  '/watched': typeof WatchedRoute
  '/drama/$id': typeof DramaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/unlocked': typeof UnlockedRoute
  '/watched': typeof WatchedRoute
  '/drama/$id': typeof DramaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/favorites': typeof FavoritesRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/unlocked': typeof UnlockedRoute
  '/watched': typeof WatchedRoute
  '/drama/$id': typeof DramaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/favorites'
    | '/invite'
    | '/profile'
    | '/subscribe'
    | '/unlocked'
    | '/watched'
    | '/drama/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/favorites'
    | '/invite'
    | '/profile'
    | '/subscribe'
    | '/unlocked'
    | '/watched'
    | '/drama/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/discover'
    | '/favorites'
    | '/invite'
    | '/profile'
    | '/subscribe'
    | '/unlocked'
    | '/watched'
    | '/drama/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  FavoritesRoute: typeof FavoritesRoute
  InviteRoute: typeof InviteRoute
  ProfileRoute: typeof ProfileRoute
  SubscribeRoute: typeof SubscribeRoute
  UnlockedRoute: typeof UnlockedRoute
  WatchedRoute: typeof WatchedRoute
  DramaIdRoute: typeof DramaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlocked': {
      id: '/unlocked'
      path: '/unlocked'
      fullPath: '/unlocked'
      preLoaderRoute: typeof UnlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watched': {
      id: '/watched'
      path: '/watched'
      fullPath: '/watched'
      preLoaderRoute: typeof WatchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drama/$id': {
      id: '/drama/$id'
      path: '/drama/$id'
      fullPath: '/drama/$id'
      preLoaderRoute: typeof DramaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  FavoritesRoute: FavoritesRoute,
  InviteRoute: InviteRoute,
  ProfileRoute: ProfileRoute,
  SubscribeRoute: SubscribeRoute,
  UnlockedRoute: UnlockedRoute,
  WatchedRoute: WatchedRoute,
  DramaIdRoute: DramaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
